apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        - name: my-app2
          image: gcr.io/koos-t-pfi-tcscc/my-app2:latest
          ports:
            - containerPort: 8080
